config/routes.rb
Rails.application.routes.draw do
  namespace :public do
    get 'favorites/index'
  end
  namespace :admin do
    resources :users, only: [:index, :show, :update, :destroy] do
    resources :posts, only: [:show, :destroy] do 
      resources :post_comments, only: [:destroy]
      end
    end
    get "search" => "searches#search"
  end

  namespace :public do
    resources :users, only: [:show, :edit, :update] do
      resource :relationships, only: [:create, :destroy]
      get "followings" => "relationships#followings", as: "followings"
      get "followers" => "relationships#followers", as: "followers"
      collection do
        get 'confirmation'
        patch 'leave'
      end
    end

    resources :posts do
      collection do
        get 'following_feed'
      end
      resources :post_comments, only: [:show, :create, :destroy]
      resources :bookmarks, only: [:index, :create, :destroy]
      resources :favorites, only: [:index, :create, :destroy]
      get "bookmarked_posts" => "posts#bookmarked"
    end
      get "search" => "searches#search"
  end
  
  root to: "homes#top"
  get 'home/about' => 'homes#about', as:'about'


  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions:      'admin/sessions',
    passwords:     'admin/passwords',
  }

  devise_for :users, skip: [:passwords], controllers: {
    sessions:      'public/sessions',
    passwords:     'public/passwords',
    registrations: 'public/registrations'
  }

  devise_scope :user do
    get "users/guest_sign_in", to: "users/sessions#guest_sign_in"
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :trackable, :recoverable, :rememberable, 
         :validatable, authentication_keys: [:email]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  #belongs_to :user
  #belongs_to :post
end

app/models/event.rb
class Event < ApplicationRecord
  #has_many :posts
  #belongs_to :user
end

app/models/favorite.rb
class Favorite < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord
  has_one_attached :post_image

  belongs_to :user
  #belongs_to :event
  #has_many :bookmarks, dependent: :destroy
  #has_many :post_comments, dependent: :destroy
  #has_many :post_tags
  #has_many :tags, through: :post_tags

  enum posts_visibility_range: { post_public: 0, post_unlisted: 1, post_private:2 }

  validates :title, presence: true
  validates :visited_at, presence: true
end

app/models/post_comment.rb
class PostComment < ApplicationRecord
  belongs_to :user
  belongs_to :post_image

  validates :comment, presence: true, length: { maximum: 200 }
end

app/models/post_tag.rb
class PostTag < ApplicationRecord
  #belongs_to :post
  #belongs_to :tag
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User", foreign_key: "follower_id"
  belongs_to :followed, class_name: "User", foreign_key: "followed_id"
end

app/models/tag.rb
class Tag < ApplicationRecord
  #has_many :post_tags
  #has_many :posts, through: :post_tags
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise  :database_authenticatable, :registerable,
          :recoverable, :rememberable, :validatable

          validates :name, presence: true
          # 名前を日本語に限定
          validates :name, format: { with: /\A[A-Za-zぁ-んァ-ヶー一-龠]+\z/, message: "は日本語で入力してください" }
          validates :introduction, length: { maximum: 300 }


          
  GUEST_USER_EMAIL = "guest@example.com"

  def self.guest
    find_or_create_by!(email: GUEST_USER_EMAIL) do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "guestuser"
    end
  end

  def guest_user?
    email == GUEST_USER_EMAIL
  end

  has_many :posts
  has_many :post_comments, dependent: :destroy
  #has_many :bookmarks, dependent: :destroy

  # フォローしているユーザーとのアクティブなリレーションシップ
  #has_many :active_relationships, class_name: "Relationship", foreign_key: "following_id", dependent: :destroy
  # フォローされているユーザーとのパッシブなリレーションシップ
  #has_many :passive_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  # フォローしているユーザーとの関連付け
  #has_many :following, through: :active_relationships, source: :followed
  # フォローされているユーザーとの関連付け
  #has_many :followers, through: :passive_relationships, source: :follower

  has_one_attached :user_image
end

app/controllers/admin/searches_controller.rb
class Admin::SearchesController < ApplicationController


  def search
    @range = params[:range]
    @word = params[:word]
  
    if @range != "User"
      @posts = Post.where("title LIKE ?", "%#{@word}%")
      return
    end

    return if @word.blank?
  
    if @word.match(/\A[a-zA-Z0-9]{10}\z/)
      @users = User.where(unique_id: @word)
    else
      @users = User.where("name LIKE ?", "%#{@word}%")
    end
  end
end

app/controllers/admin/sessions_controller.rb
# frozen_string_literal: true

class Admin::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    if @user.update(user_params)
      redirect_to admin_user_path(@user.id)
    else
      flash.now[:notice] = "更新に失敗しました。"
      render :show
    end
  end

  def destroy
  end

  private
  def user_params
    params.require(:user).permit(:is_public, :is_active)
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    public_posts_path
  end

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :introduction, :unique_id])
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  before_action :authenticate_user!

  def search
    @range = params[:range]
    @word = params[:word]
  
    if @range != "User"
      @posts = Post.where("title LIKE ?", "%#{@word}%")
      return
    end

    return if @word.blank?
  
    if @word.match(/\A[a-zA-Z0-9]{10}\z/)
      @users = User.where(unique_id: @word)
    else
      @users = User.where("name LIKE ?", "%#{@word}%")
    end
  end
end

app/helpers/admin/post_comments_helper.rb
module Admin::PostCommentsHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/admin/searches/_search.html.erb
<div class="row a-search_form">
  <%= form_with url: url_path, local: true, method: :get, class: "form-inline" do |f| %>
    <div class="col-sm-7 mb-6 a-search_form_groupe">
      <%= f.text_field :word, class: "form-control", placeholder: "キーワードを入力してください", size:30;%>
      <%= f.hidden_field :range, value: "User" %>
    </div>
    <div class="col-sm-2 a-search_form_groupe">
      <%= f.submit "Search", class: "btn search-button" %>
    </div>
  <% end %>
</div>

app/views/admin/searches/search.html.erb
<%= stylesheet_link_tag 'searched_styles' %>

<div class="container">
	<div class="row views">

    <div class="col-9 searched-content"> 
      <!-- 検索結果画面 -->
      <h2 class = "title"> Results Search</h2> 
      <div class="row results">
        <table class="table table-hover table-inverse">
          <tbody>
            <% @users.each do |user| %>
              <tr>
                <td>
                  <% if user.user_image.attached? %>
                    <%= link_to admin_user_path(user.id), class: 'post-user' do %>
                      <%= image_tag url_for(user.user_image), size: "175x150" %>
                    <% end %>
                  <% else %>
                    <%= link_to admin_user_path(user.id), class: 'post-user' do %>
                      <%= image_tag 'icon/camera.logo2.png', size: "175x150" %>
                    <% end %>
                  <% end %>
                </td>
                <td>
                  <%= link_to admin_user_path(user.id), class: 'post-user' do %>
                    <%= user.name %></td>
                  <% end %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>

  </div>
</div>

app/views/searches/_search.html.erb
<div class="row search_form">
  <%= form_with url: url_path, local: true, method: :get, class: "form-inline" do |f| %>
    <div class="col-sm-7 mb-6 search_form_groupe">
      <%= f.text_field :word, class: "form-control", placeholder: "キーワードを入力してください", size:40;%>
    </div>
    <div class="col-sm-2 mb-2 search_form_groupe">
    <%= f.collection_select :range, ["User", "Post"], :to_s, :humanize, {}, { class: "form-control" } %>    
    </div>
    <div class="col-sm-2 search_form_groupe">
      <%= f.submit "Search", class: "btn search-button" %>
    </div>
  <% end %>
</div>

app/views/searches/search.html.erb
<%= stylesheet_link_tag 'searched_styles' %>

<div class="container">
	<div class="row views">

    <div class="col-2 sidebar"> 
      <!-- サイドバー -->  
      <%= render 'public/posts/sidebar' %> 
    </div>

    <div class="col-9 searched-content"> 
      <!-- 検索結果画面 -->
      <h2 class = "title"> Results Search</h2> 
      <div class="row results">
        <table class="table table-hover table-inverse">
          <% if @range == "User" %>
            <tbody>
              <% @users.each do |user| %>
                <tr>
                  <td>
                    <% if user.user_image.attached? %>
                      <%= link_to public_user_path(user.id), class: 'post-user' do %>
                        <%= image_tag url_for(user.user_image), size: "175x150" %>
                      <% end %>
                    <% else %>
                      <%= link_to public_user_path(user.id), class: 'post-user' do %>
                        <%= image_tag 'icon/camera.logo2.png', size: "175x150" %>
                      <% end %>
                    <% end %>
                  </td>
                  <td>
                    <%= link_to public_user_path(user.id), class: 'post-user' do %>
                      <%= user.name %></td>
                    <% end %>
                </tr>
              <% end %>
            </tbody>
          <% else %>
            <tbody>
              <% @posts.each do |post| %>
                <tr>
                  <td>
                    <% if post.post_image.attached? %>
                      <%= link_to public_post_path(post), class: 's-post-image' do %>
                        <%= image_tag url_for(post.post_image), size: "175x150" %>
                      <% end %>
                    <% else %>
                      <%= link_to public_post_path(post), class: 's-post-image' do %>
                        <%= image_tag 'noimage.png', size: "175x150" %>
                      <% end %>
                    <% end %>
                  </td>
                  <td>
                    <%= link_to public_post_path(post), class: 's-post-title' do %>
                      <%= post.title %>
                    <% end %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          <% end %>
        </table>
      </div>
    </div>
  </div>
</div>