config/routes.rb
Rails.application.routes.draw do
  namespace :public do
    get 'favorites/index'
  end
  namespace :admin do
    resources :users, only: [:index, :show, :update, :destroy] do
    resources :posts, only: [:show, :destroy] do 
      resources :post_comments, only: [:destroy]
      end
    end
    get "search" => "searches#search"
  end

  namespace :public do
    resources :users, only: [:show, :edit, :update] do
      resource :relationships, only: [:create, :destroy]
      get "followings" => "relationships#followings", as: "followings"
      get "followers" => "relationships#followers", as: "followers"
      collection do
        get 'confirmation'
        patch 'leave'
      end
    end

    resources :posts do
      collection do
        get 'following_feed'
      end
      resources :post_comments, only: [:show, :create, :destroy]
      resources :bookmarks, only: [:index, :create, :destroy]
      resources :favorites, only: [:index, :create, :destroy]
      get "bookmarked_posts" => "posts#bookmarked"
    end
      get "search" => "searches#search"
  end
  
  root to: "homes#top"
  get 'home/about' => 'homes#about', as:'about'


  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions:      'admin/sessions',
    passwords:     'admin/passwords',
  }

  devise_for :users, skip: [:passwords], controllers: {
    sessions:      'public/sessions',
    passwords:     'public/passwords',
    registrations: 'public/registrations'
  }

  devise_scope :user do
    get "users/guest_sign_in", to: "users/sessions#guest_sign_in"
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :trackable, :recoverable, :rememberable, 
         :validatable, authentication_keys: [:email]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  #belongs_to :user
  #belongs_to :post
end

app/models/event.rb
class Event < ApplicationRecord
  #has_many :posts
  #belongs_to :user
end

app/models/favorite.rb
class Favorite < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord
  has_one_attached :post_image

  belongs_to :user
  #belongs_to :event
  #has_many :bookmarks, dependent: :destroy
  #has_many :post_comments, dependent: :destroy
  #has_many :post_tags
  #has_many :tags, through: :post_tags

  enum posts_visibility_range: { post_public: 0, post_unlisted: 1, post_private:2 }

  validates :title, presence: true
  validates :visited_at, presence: true
end

app/models/post_comment.rb
class PostComment < ApplicationRecord
  belongs_to :user
  belongs_to :post_image

  validates :comment, presence: true, length: { maximum: 200 }
end

app/models/post_tag.rb
class PostTag < ApplicationRecord
  #belongs_to :post
  #belongs_to :tag
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User", foreign_key: "follower_id"
  belongs_to :followed, class_name: "User", foreign_key: "followed_id"
end

app/models/tag.rb
class Tag < ApplicationRecord
  #has_many :post_tags
  #has_many :posts, through: :post_tags
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise  :database_authenticatable, :registerable,
          :recoverable, :rememberable, :validatable

          validates :name, presence: true
          # 名前を日本語に限定
          validates :name, format: { with: /\A[A-Za-zぁ-んァ-ヶー一-龠]+\z/, message: "は日本語で入力してください" }
          validates :introduction, length: { maximum: 300 }


          
  GUEST_USER_EMAIL = "guest@example.com"

  def self.guest
    find_or_create_by!(email: GUEST_USER_EMAIL) do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "guestuser"
    end
  end

  def guest_user?
    email == GUEST_USER_EMAIL
  end

  has_many :posts
  has_many :post_comments, dependent: :destroy
  #has_many :bookmarks, dependent: :destroy

  # フォローしているユーザーとのアクティブなリレーションシップ
  #has_many :active_relationships, class_name: "Relationship", foreign_key: "following_id", dependent: :destroy
  # フォローされているユーザーとのパッシブなリレーションシップ
  #has_many :passive_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  # フォローしているユーザーとの関連付け
  #has_many :following, through: :active_relationships, source: :followed
  # フォローされているユーザーとの関連付け
  #has_many :followers, through: :passive_relationships, source: :follower

  has_one_attached :user_image
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    if @user.update(user_params)
      redirect_to admin_user_path(@user.id)
    else
      flash.now[:notice] = "更新に失敗しました。"
      render :show
    end
  end

  def destroy
  end

  private
  def user_params
    params.require(:user).permit(:is_public, :is_active)
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    public_posts_path
  end

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :introduction, :unique_id])
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  before_action :authenticate_user!

  def search
    @range = params[:range]
    @word = params[:word]
  
    if @range != "User"
      @posts = Post.where("title LIKE ?", "%#{@word}%")
      return
    end

    return if @word.blank?
  
    if @word.match(/\A[a-zA-Z0-9]{10}\z/)
      @users = User.where(unique_id: @word)
    else
      @users = User.where("name LIKE ?", "%#{@word}%")
    end
  end
end

app/helpers/admin/post_comments_helper.rb
module Admin::PostCommentsHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/layouts/_footer.html.erb
<footer>
  <div class="container">
    <div class="row">
      <div class="mx-auto">
          <%= image_tag("icon/Title.png", alt: "Logo", width: 150, height: 40, class: "d-inline-block align-text-top mr-2") %>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="custom">
    <nav class="navbar navbar-expand-lg navbar-light">
      <div class="container">
        <!-- ロゴ --> 
        <div class="row">
          <%= link_to root_path do %>
            <%= image_tag("icon/logo.png", alt: "Logo", width: 200, height: 75, class: "d-inline-block align-text-top mr-2") %>
          <% end %>
        </div>
        <div class="flash">
          <%= flash[:comment] %>
        </div>
        <!-- メニュー --> 
        <div class="row">
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <% if admin_signed_in?  %>
              <!-- アドミンヘッダー --> 
                <li class="nav-item" style="padding-left: 10px;">
                  <%= link_to 'Top', root_path, class: 'btn btn-custom', style: 'font-size: 20px;' %>
                </li>
                <li class="nav-item" style="padding-left: 10px;">
                  <%= link_to 'Users', admin_users_path, class: 'btn btn-custom', style: 'font-size: 20px;' %>
                </li>
                <li class="nav-item" style="padding-left: 10px;">
                  <%= link_to 'Log out', destroy_admin_session_path, class: 'btn btn-custom', style: 'font-size: 20px;', method: :delete %>
                </li>

              <% elsif user_signed_in? %>
              <!-- ユーザーヘッダー --> 
                <li class="nav-item" style="padding-left: 10px;">
                  <%= link_to 'Home', public_posts_path, class: 'btn btn-custom', style: 'font-size: 20px;' %>
                </li>
                <li class="nav-item" style="padding-left: 10px;">
                  <%= link_to 'New', new_public_post_path, class: 'btn btn-custom', style: 'font-size: 20px;' %>
                </li>
                <li class="nav-item" style="padding-left: 10px;">
                  <%= link_to 'MyPage', public_user_path(current_user.id), class: 'btn btn-custom', style: 'font-size: 20px;' %>
                </li>
                <li class="nav-item" style="padding-left: 10px;">
                  <%= link_to 'Log out',destroy_user_session_path, class: 'btn btn-custom', style: 'font-size: 20px;', method: :delete %>
                </li>

              <% else %>
              <!-- 非ログイン時 --> 
                <li class="nav-item" style="padding-left: 10px;">
                  <%= link_to 'About', about_path, class: 'btn btn-custom', style: 'font-size: 20px;' %>
                </li>
                <li class="nav-item" style="padding-left: 10px;">
                  <%= link_to 'Home', public_posts_path, class: 'btn btn-custom', style: 'font-size: 20px;' %>
                </li>
                <li class="nav-item" style="padding-left: 10px;">
                  <%= link_to 'Log in', new_user_session_path, class: 'btn btn-custom', style: 'font-size: 20px;' %>
                </li>
                <li class="nav-item" style="padding-left: 10px;">
                  <%= link_to 'Sing up', new_user_registration_path, class: 'btn btn-custom', style: 'font-size: 20px;' %>
              </li>
              <% end %>
            </ul>
          </div>
        </div>
      </div>
    </nav>
  </header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PFRetrogia</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/2e273f30f7.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'application', 'custom_styles' %>
  </head>

  <body class="d-flex flex-column vh-100 ">
    <%= render 'layouts/header' %>

    <%= yield %>

    <%= render 'layouts/footer' %>
  </body>
</html>